server:
  port: 8080

spring:
  #  redis:
  #    host: host.docker.internal
  #    port: 6379
  jackson:
    parser:
      allow-numeric-leading-zeros: true
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/game?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: wine01!
    driver-class-name: com.mysql.cj.jdbc.Driver