server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/game
    username: your_user_name
    password: your_user_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true